### ISSUE TITLE
74,0 Mb big geoclue package could not be transfered

### ISSUE THREAD

**Issue by temaleva** [nemomobile-ux/nemo-packaging#170]
Trying to execute pacman -S  $(pacman -Slq nemomobile) on manjaro

get the exception:

Could not transfer 'geoclue1-providers-mlsdb-0.1.7-3-x86_64.pkg.tar.zst' from img.nemomobile.net : Maximum file size exceeded

**Comment by temaleva** [comment]
The requested URL returned error: 404

**Comment by neochapay** [comment]
> The requested URL returned error: 404

pacman -Syy
